publicVariable "DT_fnc_companyCreated";
publicVariable "DT_fnc_companyDeleted";
publicVariable "DT_fnc_companyLBChanged";
publicVariable "DT_fnc_createCompany";
publicVariable "DT_fnc_deleteCompany";
publicVariable "DT_fnc_invitedPlayer";
publicVariable "DT_fnc_manageCompany";
publicVariable "DT_fnc_openCompanyMenu";
publicVariable "DT_fnc_showCompany";
