class Civilian {
	file = "Dom_Code\Civilian";
	class catchFish {};
	class endDelivery {};
	class initBombMenu {};
	class knockedDown {};
	class knockOut {};
	class questionLocation {};
	class repairTerrainObject {};
	class robStore {};
	class startDelivery {};
	class startJailbreak {};
	class startRaid {};
	class switchJob {};
	class taxiDistance {};
	class updateGov {};
	class ziptie {};
	class ziptied {};
};
